# -*- coding: utf-8 -*-
"""TASK 2—EMOTION RECOGNITION FROM SPEECH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hd7Ntlu4jRqX_5w-49Z1WsUUD5scNjcK

# ═════════════════════════════════════════════════════
# 🎙️  TASK 2 — ADVANCED EMOTION RECOGNITION FROM SPEECH
# ═════════════════════════════════════════════════════
#  Developer    : Taj Wali Khan
#  Internship   : CodeAlpha Machine Learning Internship
#  Dataset      : RAVDESS (1,440 speech audio files · 8 emotions)
#  Architecture : SE-CNN → Multi-Head Self-Attention → BiLSTM
#                 → Temporal Attention Pooling → Dense Head
#  Input Format : Stacked 3-Channel Spectrograms (MFCC + ΔMFCC + ΔΔMFCC)
#  Loss         : Focal Loss (better than CrossEntropy on imbalanced data)
#  Augmentation : Time Stretch + Pitch Shift + Noise + SpecAugment
#  Evaluation   : Confusion Matrix + Per-Class ROC-AUC + t-SNE Embeddings
#  Deployment   : Advanced 6-Tab Gradio Web App with Live Visualizations
#  Platform     : Google Colab (T4 GPU recommended)
# ═════════════════════════════════════════════════════

# ╔══════════════════════════════════════════════
#   CELL 1 — Install Required Libraries                              
#   Run this cell first. Takes about 60–90 seconds.                    
# ╚═════════════════════════════════════════════
"""

get_ipython().system('pip install -q librosa soundfile gradio scikit-learn matplotlib seaborn')
print("✅ All libraries installed successfully!")

"""
# ╔══════════════════════════════════════════════════
# ║  CELL 2 — Global Configuration                                      
# ║  All tunable constants live here. Easy to find and change.          
# ╚════════════════════════════════════════════════"""

# ── Audio settings ────────────────────────────────────────────────────
SAMPLE_RATE  = 22050     # Standard audio sample rate (Hz)
DURATION     = 3.0       # Fixed audio clip length (seconds)
HOP_LENGTH   = 512       # Frames between consecutive STFT windows
N_FFT        = 2048      # FFT window size
N_MFCC       = 40        # Number of MFCC coefficients to extract
N_MELS       = 128       # Mel filterbank bins (for Mel Spectrogram)
TIME_STEPS   = 130       # Fixed time frames after padding/truncation

# ── Training settings ─────────────────────────────────────────────────
BATCH_SIZE   = 32
MAX_EPOCHS   = 100       # EarlyStopping will usually stop earlier
TEST_SIZE    = 0.15      # 15% test split
VAL_SIZE     = 0.15      # 15% validation split
RANDOM_SEED  = 42

# ── Augmentation settings ─────────────────────────────────────────────
TIME_STRETCH_RANGE = (0.85, 1.15)   # ±15% time stretch
PITCH_SHIFT_RANGE  = (-2, 2)        # ±2 semitones pitch shift
NOISE_LEVEL        = 0.003          # Gaussian noise amplitude
SPEC_TIME_MASK     = 15             # Max time frames to mask (SpecAugment)
SPEC_FREQ_MASK     = 8              # Max freq bins to mask (SpecAugment)

# ── Dataset settings ──────────────────────────────────────────────────
EMOTION_MAP = {
    '01': 'neutral',  '02': 'calm',     '03': 'happy',    '04': 'sad',
    '05': 'angry',    '06': 'fearful',  '07': 'disgust',  '08': 'surprised'
}
EMOTION_EMOJI = {
    'neutral':'😐', 'calm':'😌', 'happy':'😊', 'sad':'😢',
    'angry':'😠',   'fearful':'😨','disgust':'🤢','surprised':'😲'
}
EMOTION_COLORS = {
    'neutral':'#95a5a6','calm':'#3498db','happy':'#f1c40f','sad':'#2980b9',
    'angry':'#e74c3c',  'fearful':'#9b59b6','disgust':'#27ae60','surprised':'#e67e22'
}

"""
# ╔════════════════════════════════════════════════════
# ║  CELL 3 — Imports                                                   
# ╚════════════════════════════════════════════════════"""

import os, warnings, zipfile, pickle
import urllib.request
import numpy       as np
import pandas      as pd
import librosa
import librosa.display
import soundfile   as sf
import matplotlib.pyplot  as plt
import matplotlib.gridspec as gridspec
import seaborn     as sns
import gradio      as gr

import tensorflow  as tf
from tensorflow                 import keras
from tensorflow.keras           import layers, callbacks
from tensorflow.keras.utils     import plot_model

from sklearn.model_selection    import train_test_split
from sklearn.preprocessing      import StandardScaler, LabelEncoder
from sklearn.metrics            import (confusion_matrix, classification_report,
                                         roc_auc_score, roc_curve)
from sklearn.manifold           import TSNE

warnings.filterwarnings('ignore')
np.random.seed(RANDOM_SEED)
tf.random.set_seed(RANDOM_SEED)

plt.rcParams.update({
    'figure.facecolor' : 'white',
    'axes.facecolor'   : '#f8f9fa',
    'axes.spines.top'  : False,
    'axes.spines.right': False,
    'font.family'      : 'DejaVu Sans'
})

print(f"✅ All imports loaded!")
print(f"   TensorFlow : {tf.__version__}")
gpu = tf.config.list_physical_devices('GPU')
print(f"   GPU        : {'Detected ✅' if gpu else 'Not found ⚠️  — go to Runtime → Change Runtime Type → T4 GPU'}")

"""
# ╔════════════════════════════════════════════
# ║  CELL 4 — Download & Parse RAVDESS Dataset                          
# ╚════════════════════════════════════════════
# RAVDESS: 24 professional actors (12 male, 12 female), 8 emotions.
# Filename format: 03-01-{emotion_code}-01-02-01-{actor}.wav
# We read the emotion code from position index 2 in the filename."""

RAVDESS_URL   = "https://zenodo.org/record/1188976/files/Audio_Speech_Actors_01-24.zip"
DOWNLOAD_PATH = "/tmp/ravdess.zip"
EXTRACT_PATH  = "/tmp/ravdess"

def download_with_progress(url, path):
    """Downloads a file and shows progress every 10%."""
    def reporthook(count, block_size, total_size):
        pct = min(100, count * block_size * 100 / total_size)
        if count % 200 == 0:
            downloaded_mb = count * block_size / (1024**2)
            total_mb      = total_size / (1024**2)
            print(f"   ↓ {pct:5.1f}%  ({downloaded_mb:.0f} MB / {total_mb:.0f} MB)", end='\r')
    urllib.request.urlretrieve(url, path, reporthook=reporthook)
    print()

if not os.path.exists(EXTRACT_PATH):
    print("📥 Downloading RAVDESS dataset (~440 MB) ...")
    print("   Expected time: 3–8 minutes (depends on connection speed)\n")
    download_with_progress(RAVDESS_URL, DOWNLOAD_PATH)
    print("📦 Extracting audio files...")
    with zipfile.ZipFile(DOWNLOAD_PATH, 'r') as zf:
        zf.extractall(EXTRACT_PATH)
    os.remove(DOWNLOAD_PATH)   # Free disk space
    print("✅ Dataset ready!\n")
else:
    print("✅ Dataset already cached — skipping download.\n")

# ── Parse file paths and extract labels ───────────────────────────────
file_records = []
for root, _, files in os.walk(EXTRACT_PATH):
    for fname in sorted(files):
        if not fname.endswith('.wav'):
            continue
        parts = fname.replace('.wav','').split('-')
        if len(parts) >= 7 and parts[2] in EMOTION_MAP:
            file_records.append({
                'path'       : os.path.join(root, fname),
                'emotion'    : EMOTION_MAP[parts[2]],
                'actor_id'   : int(parts[6]),
                'intensity'  : 'normal' if parts[3] == '01' else 'strong',
                'gender'     : 'female' if int(parts[6]) % 2 == 0 else 'male'
            })

df = pd.DataFrame(file_records)

print(f"📊 Dataset Overview:")
print(f"   Total audio files  : {len(df)}")
print(f"   Unique emotions    : {df['emotion'].nunique()}  →  {sorted(df['emotion'].unique())}")
print(f"   Unique actors      : {df['actor_id'].nunique()}")
print(f"\n   Emotion Distribution:")
for emotion, count in df['emotion'].value_counts().items():
    bar = '█' * (count // 3)
    print(f"   {EMOTION_EMOJI[emotion]} {emotion:12s}  {bar}  {count}")

"""
# ╔═══════════════════════════════════════════════════
# ║  CELL 5 — Exploratory Data Analysis (EDA)                          
# ╚═══════════════════════════════════════════════════"""

fig = plt.figure(figsize=(18, 10))
fig.suptitle("🎙️ RAVDESS Dataset — Exploratory Data Analysis",
             fontsize=16, fontweight='bold', y=1.01)
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.40, wspace=0.35)

# 1 — Class distribution
ax1 = fig.add_subplot(gs[0, 0])
emotions_sorted = df['emotion'].value_counts()
colors          = [EMOTION_COLORS[e] for e in emotions_sorted.index]
bars = ax1.barh(emotions_sorted.index, emotions_sorted.values,
                color=colors, edgecolor='white', height=0.7)
ax1.bar_label(bars, padding=3, fontsize=9)
ax1.set_title("Emotion Distribution", fontweight='bold')
ax1.set_xlabel("Number of Files")

# 2 — Gender split per emotion
ax2 = fig.add_subplot(gs[0, 1])
gender_pivot = df.groupby(['emotion','gender']).size().unstack(fill_value=0)
gender_pivot.plot(kind='bar', ax=ax2, color=['#e74c3c','#3498db'],
                  edgecolor='white', width=0.7)
ax2.set_title("Files per Emotion by Gender", fontweight='bold')
ax2.set_xlabel(""); ax2.tick_params(axis='x', rotation=35)
ax2.legend(['Female','Male'])

# 3 — Intensity split
ax3 = fig.add_subplot(gs[0, 2])
intens_pivot = df.groupby(['emotion','intensity']).size().unstack(fill_value=0)
intens_pivot.plot(kind='bar', ax=ax3, color=['#f39c12','#8e44ad'],
                  edgecolor='white', width=0.7)
ax3.set_title("Normal vs Strong Intensity", fontweight='bold')
ax3.set_xlabel(""); ax3.tick_params(axis='x', rotation=35)

# 4 — Waveform comparison (4 emotions)
selected_emotions = ['happy','sad','angry','calm']
for i, emo in enumerate(selected_emotions):
    ax = fig.add_subplot(gs[1, i % 3]) if i < 3 else None
    if ax is None:
        break
    sample = df[df['emotion'] == emo].iloc[0]['path']
    y_wav, _  = librosa.load(sample, sr=SAMPLE_RATE, duration=DURATION)
    y_wav     = librosa.util.fix_length(y_wav, size=int(SAMPLE_RATE * DURATION))
    t         = np.linspace(0, DURATION, len(y_wav))
    ax.plot(t, y_wav, color=EMOTION_COLORS[emo], linewidth=0.8)
    ax.fill_between(t, y_wav, alpha=0.25, color=EMOTION_COLORS[emo])
    ax.set_title(f"{EMOTION_EMOJI[emo]} {emo.upper()} — Waveform", fontweight='bold')
    ax.set_xlabel("Time (s)");  ax.set_ylabel("Amplitude")

plt.savefig('/tmp/task2_eda.png', dpi=150, bbox_inches='tight')
plt.show()
print("💾 EDA chart saved → /tmp/task2_eda.png")

"""
# ╔════════════════════════════════════════════════
# ║  CELL 6 — Advanced Feature Extraction                               
# ║                                                                     
# ║  Instead of extracting a flat feature vector, I'm building a       
# ║  3-channel "spectrogram image" per audio file:                      
# ║                                                                     
# ║   Channel 0 → MFCC          (static timbre snapshot)               
# ║   Channel 1 → Δ  MFCC       (how timbre is changing)               
# ║   Channel 2 → ΔΔ MFCC       (rate of change of change)             
# ║                                                                     
# ║  This is exactly how state-of-the-art speech models encode audio.  
# ║  Shape per sample: (N_MFCC=40, TIME_STEPS=130, channels=3)         
# ╚══════════════════════════════════════════════════"""

def normalize_feature(x):
    """Zero-mean, unit-variance normalization per feature map."""
    return (x - x.mean()) / (x.std() + 1e-8)


def fix_time_dim(x, length=TIME_STEPS):
    """Pad with zeros or truncate to a fixed number of time frames."""
    if x.shape[1] < length:
        pad_width = length - x.shape[1]
        x = np.pad(x, ((0,0),(0,pad_width)), mode='constant', constant_values=0)
    return x[:, :length]


def spec_augment(feature_3ch):
    """
    SpecAugment (Park et al., 2019) — randomly masks time frames
    and frequency bands to force the model to be more robust.
    This is applied ONLY during training, not at inference.
    """
    out = feature_3ch.copy()
    F, T, C = out.shape

    # Time masking: zero out random contiguous time frames
    for _ in range(2):
        t  = np.random.randint(0, max(1, SPEC_TIME_MASK))
        t0 = np.random.randint(0, max(1, T - t))
        out[:, t0:t0+t, :] = 0.0

    # Frequency masking: zero out random contiguous frequency bands
    for _ in range(2):
        f  = np.random.randint(0, max(1, SPEC_FREQ_MASK))
        f0 = np.random.randint(0, max(1, F - f))
        out[f0:f0+f, :, :] = 0.0

    return out


def audio_augment(y):
    """
    Waveform-level augmentation — randomly applies one of four methods.
    This doubles the variety in our training set without extra recordings.
    """
    choice = np.random.choice(['none','stretch','pitch','noise'])
    if choice == 'stretch':
        rate = np.random.uniform(*TIME_STRETCH_RANGE)
        y    = librosa.effects.time_stretch(y, rate=rate)
    elif choice == 'pitch':
        steps = np.random.randint(*PITCH_SHIFT_RANGE)
        y     = librosa.effects.pitch_shift(y, sr=SAMPLE_RATE, n_steps=int(steps))
    elif choice == 'noise':
        y = y + NOISE_LEVEL * np.random.randn(len(y))
    return librosa.util.fix_length(y, size=int(SAMPLE_RATE * DURATION))


def extract_3ch_feature(file_path, augment=False):
    """
    Core feature extraction function.
    Loads audio → optionally augments → extracts 3-channel MFCC image.

    Returns:
        np.ndarray of shape (N_MFCC, TIME_STEPS, 3)  or  None on error
    """
    try:
        y, _ = librosa.load(file_path, sr=SAMPLE_RATE, duration=DURATION)
        y    = librosa.util.fix_length(y, size=int(SAMPLE_RATE * DURATION))

        if augment:
            y = audio_augment(y)

        # ── Extract MFCC and its first and second derivatives ──────────
        mfcc    = librosa.feature.mfcc(y=y, sr=SAMPLE_RATE, n_mfcc=N_MFCC,
                                        n_fft=N_FFT, hop_length=HOP_LENGTH)
        delta   = librosa.feature.delta(mfcc)
        delta2  = librosa.feature.delta(mfcc, order=2)

        # ── Normalize each feature map independently ────────────────────
        mfcc   = normalize_feature(mfcc)
        delta  = normalize_feature(delta)
        delta2 = normalize_feature(delta2)

        # ── Pad or truncate to fixed TIME_STEPS ────────────────────────
        mfcc   = fix_time_dim(mfcc)
        delta  = fix_time_dim(delta)
        delta2 = fix_time_dim(delta2)

        # ── Stack as 3-channel image: (40, 130, 3) ─────────────────────
        feature_3ch = np.stack([mfcc, delta, delta2], axis=-1).astype('float32')

        # Apply SpecAugment during training
        if augment:
            feature_3ch = spec_augment(feature_3ch)

        return feature_3ch

    except Exception as exc:
        print(f"⚠️  Skipping {os.path.basename(file_path)}: {exc}")
        return None


# Quick sanity check
test_feat = extract_3ch_feature(df['path'].iloc[0])
print(f"✅ Feature extraction test passed!")
print(f"\n   Input shape per sample : {test_feat.shape}")
print(f"   ├─ Axis 0 ({N_MFCC})   : MFCC coefficients (frequency axis)")
print(f"   ├─ Axis 1 ({TIME_STEPS})  : Time frames")
print(f"   └─ Axis 2 (3)   : Channels — [MFCC, Δ MFCC, ΔΔ MFCC]")

"""
# ╔══════════════════════════════════════════════
# ║  CELL 7 — Visualize the 3-Channel Feature Maps                     ╚═════════════════════════════════════════════
# This gives us a visual understanding of what the model "sees"
# for each emotion before any learning takes place."""

fig, axes = plt.subplots(4, 3, figsize=(18, 14))
fig.suptitle("🔬 3-Channel Feature Maps per Emotion\n"
             "(MFCC  |  Δ MFCC  |  ΔΔ MFCC)",
             fontsize=14, fontweight='bold')

emotions_viz = ['happy','sad','angry','calm']
channel_names = ['MFCC (Static)', 'Δ MFCC (Velocity)', 'ΔΔ MFCC (Acceleration)']
cmaps         = ['viridis', 'coolwarm', 'plasma']

for row, emotion in enumerate(emotions_viz):
    sample_path = df[df['emotion'] == emotion].iloc[0]['path']
    feat_3ch    = extract_3ch_feature(sample_path, augment=False)
    for ch in range(3):
        ax = axes[row, ch]
        im = ax.imshow(feat_3ch[:, :, ch], aspect='auto', origin='lower',
                       cmap=cmaps[ch], interpolation='nearest')
        if row == 0:
            ax.set_title(channel_names[ch], fontweight='bold', fontsize=11)
        if ch == 0:
            ax.set_ylabel(f"{EMOTION_EMOJI[emotion]} {emotion.upper()}",
                          fontweight='bold', fontsize=10)
        ax.set_xlabel("Time Frames")
        plt.colorbar(im, ax=ax, shrink=0.8)

plt.tight_layout()
plt.savefig('/tmp/task2_feature_maps.png', dpi=150, bbox_inches='tight')
plt.show()
print("💾 Feature maps saved → /tmp/task2_feature_maps.png")

"""
# ╔═══════════════════════════════════════════════
# ║  CELL 8 — Build the Complete Feature Dataset                        
# ╚═══════════════════════════════════════════════
# For each audio file, we create TWO samples:
#   1. The original recording (no augmentation)
#   2. An augmented version  (random stretch/pitch/noise + SpecAugment)
# This effectively doubles our training data"""

le          = LabelEncoder()
df['label'] = le.fit_transform(df['emotion'])
NUM_CLASSES  = len(le.classes_)
EMOTION_NAMES = list(le.classes_)

print(f"⏳ Extracting features from {len(df)} audio files...")
print(f"   (×2 with augmentation = {len(df)*2} total samples)\n")

X_list, y_list = [], []

for i, (_, row) in enumerate(df.iterrows()):
    # Original
    feat = extract_3ch_feature(row['path'], augment=False)
    if feat is not None:
        X_list.append(feat)
        y_list.append(row['label'])

    # Augmented copy
    feat_aug = extract_3ch_feature(row['path'], augment=True)
    if feat_aug is not None:
        X_list.append(feat_aug)
        y_list.append(row['label'])

    if (i + 1) % 120 == 0 or (i + 1) == len(df):
        print(f"   [{i+1:4d}/{len(df)}] files done — {len(X_list)} samples so far")

X = np.array(X_list, dtype='float32')   # (N, 40, 130, 3)
y = np.array(y_list, dtype='int32')     # (N,)

print(f"\n✅ Feature matrix built!")
print(f"   Shape: {X.shape}  ({X.nbytes/(1024**2):.1f} MB)")
print(f"   Labels: {y.shape}  unique values: {np.unique(y)}")

"""
# ╔════════════════════════════════════════════════════
# ║  CELL 9 — Preprocessing: Split & Scale                              
# ╚════════════════════════════════════════════════════"""

# 70% train  |  15% validation  |  15% test  (stratified splits)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=TEST_SIZE + VAL_SIZE,
    random_state=RANDOM_SEED, stratify=y)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50,
    random_state=RANDOM_SEED, stratify=y_temp)

print(f"📦 Split Summary:")
print(f"   Train       : {X_train.shape[0]} samples  ({X_train.shape[0]/len(X)*100:.0f}%)")
print(f"   Validation  : {X_val.shape[0]}   samples  ({X_val.shape[0]/len(X)*100:.0f}%)")
print(f"   Test        : {X_test.shape[0]}   samples  ({X_test.shape[0]/len(X)*100:.0f}%)")

# Feature-wise standardization (applied per channel independently)
# We compute statistics from training data only — no data leakage
scaler  = StandardScaler()
orig_shape = X_train.shape

X_train_s = scaler.fit_transform(X_train.reshape(-1, N_MFCC * TIME_STEPS * 3))\
                  .reshape(orig_shape)
X_val_s   = scaler.transform(X_val.reshape(-1, N_MFCC * TIME_STEPS * 3))\
                  .reshape(X_val.shape)
X_test_s  = scaler.transform(X_test.reshape(-1, N_MFCC * TIME_STEPS * 3))\
                  .reshape(X_test.shape)

print(f"\n✅ Scaling complete (StandardScaler fit on training set only)")
print(f"   Final input shape to model: {X_train_s.shape}")

"""

# ╔══════════════════════════════════════════════
# ║  CELL 10 — Advanced Model Architecture                              
# ║                                                                     
# ║  SE-CNN  → Multi-Head Self-Attention  → BiLSTM  → Temporal Attn   
# ║                                                                     
# ║  Input (40, 130, 3)                                                 
# ║    ↓ SE-CNN Block 1 (64 filters + channel attention)                
# ║    ↓ SE-CNN Block 2 (128 filters + channel attention)               
# ║    ↓ SE-CNN Block 3 (256 filters + channel attention)               
# ║    ↓ Permute + Pool → (batch, time=32, features=256)               
# ║    ↓ Multi-Head Self-Attention (4 heads, key_dim=64)               
# ║    ↓ Add + LayerNorm (residual connection)                          
# ║    ↓ BiLSTM (128 units, forward + backward)                         
# ║    ↓ BiLSTM (64 units, forward + backward)                          
# ║    ↓ Temporal Attention Pooling (soft-weight over time)             
# ║    ↓ Dense(256) → BN → Dropout(0.4)                                
# ║    ↓ Dense(128) → Dropout(0.3)                                      
# ║    ↓ Dense(8, softmax) → 8 emotion probabilities                   
# ╚═══════════════════════════════════════════════"""

def freq_pooling(t):
    return tf.reduce_mean(t, axis=2)

def temporal_pooling(t):
    return tf.reduce_sum(t, axis=1)

def se_block(x, ratio=16, name=''):
    channels = x.shape[-1]
    r = max(1, channels // ratio)
    se = layers.GlobalAveragePooling2D(name=f'{name}_squeeze')(x)
    se = layers.Dense(r, activation='relu', name=f'{name}_excite_fc1')(se)
    se = layers.Dense(channels, activation='sigmoid', name=f'{name}_excite_fc2')(se)
    se = layers.Reshape((1, 1, channels), name=f'{name}_reshape')(se)
    return layers.Multiply(name=f'{name}_scale')([x, se])

def cnn_block(x, filters, pool_size=(2,2), dropout_rate=0.25, name=''):
    x = layers.Conv2D(filters, (3,3), padding='same', activation='relu', name=f'{name}_conv')(x)
    x = layers.BatchNormalization(name=f'{name}_bn')(x)
    x = se_block(x, ratio=max(1, filters//16), name=f'{name}_se')
    x = layers.MaxPooling2D(pool_size, name=f'{name}_pool')(x)
    x = layers.Dropout(dropout_rate, name=f'{name}_drop')(x)
    return x

def build_advanced_model(input_shape=(N_MFCC, TIME_STEPS, 3), num_classes=8):
    inputs = keras.Input(shape=input_shape, name='mfcc_3ch_input')
    x = cnn_block(inputs, filters=64, pool_size=(2,2), dropout_rate=0.20, name='cnn1')
    x = cnn_block(x, filters=128, pool_size=(2,2), dropout_rate=0.25, name='cnn2')
    x = cnn_block(x, filters=256, pool_size=(2,1), dropout_rate=0.30, name='cnn3')
    x = layers.Permute((2, 1, 3), name='permute_time_first')(x)
    x = layers.Lambda(freq_pooling, output_shape=(32, 256), name='freq_avg_pool')(x)
    attn_out = layers.MultiHeadAttention(num_heads=4, key_dim=64, dropout=0.10, name='mhsa')(query=x, value=x, key=x)
    x = layers.Add(name='attn_residual')([x, attn_out])
    x = layers.LayerNormalization(name='attn_layernorm')(x)
    x = layers.Bidirectional(layers.LSTM(128, return_sequences=True, dropout=0.25), name='bilstm1')(x)
    x = layers.Bidirectional(layers.LSTM(64, return_sequences=True, dropout=0.20), name='bilstm2')(x)
    attn_scores = layers.Dense(1, activation='tanh', name='temporal_scores')(x)
    attn_weights = layers.Softmax(axis=1, name='temporal_weights')(attn_scores)
    x = layers.Multiply(name='weighted_seq')([x, attn_weights])
    x = layers.Lambda(temporal_pooling, output_shape=(128,), name='temporal_pool')(x)
    x = layers.Dense(256, activation='relu', name='embedding')(x)
    x = layers.BatchNormalization(name='head_bn')(x)
    x = layers.Dropout(0.40, name='head_drop1')(x)
    x = layers.Dense(128, activation='relu', name='dense2')(x)
    x = layers.Dropout(0.30, name='head_drop2')(x)
    out = layers.Dense(num_classes, activation='softmax', dtype='float32', name='predictions')(x)
    return keras.Model(inputs, out, name='SE_CNN_MHA_BiLSTM')

model = build_advanced_model(input_shape=(40, 130, 3), num_classes=NUM_CLASSES)
model.summary()

"""
# ╔════════════════════════════════════════════════════
# ║  CELL 11 — Focal Loss & Compile                                     
# ║                                                                     
# ║  Standard CrossEntropy treats every misclassification equally.      
# ║  Focal Loss down-weights easy examples and focuses training on      
# ║  hard ones — perfect for emotion recognition where some emotions    
# ║  (e.g., disgust) are much harder to learn than others (e.g., happy)
# ╚══════════════════════════════════════════════════"""

# Re-compiling the model to ensure it is ready for training
STEPS_PER_EPOCH = X_train_s.shape[0] // BATCH_SIZE
lr_schedule     = keras.optimizers.schedules.CosineDecayRestarts(
    initial_learning_rate = 1e-3,
    first_decay_steps     = STEPS_PER_EPOCH * 20,
    t_mul                 = 1.5,
    m_mul                 = 0.90,
    alpha                 = 1e-6
)

model.compile(
    optimizer = keras.optimizers.Adam(lr_schedule, clipnorm=1.0),
    loss      = FocalLoss(gamma=2.0, alpha=0.25, num_classes=NUM_CLASSES),
    metrics   = ['accuracy']
)

print("✅ Model re-compiled successfully!")

"""
# ╔═════════════════════════════════════════════════════
# ║  CELL 12 — Train with Advanced Callbacks                            
# ╚═════════════════════════════════════════════════════"""

checkpoint_path = '/tmp/task2_adv_best_v2.keras'

cb_list = [
    callbacks.EarlyStopping(
        monitor='val_accuracy',
        patience=18,
        restore_best_weights=True,
        mode='max',
        verbose=1
    ),
    callbacks.ModelCheckpoint(
        filepath=checkpoint_path,
        monitor='val_accuracy',
        save_best_only=True,
        mode='max',
        verbose=0
    ),
    callbacks.LambdaCallback(
        on_epoch_end=lambda epoch, logs: print(
            f"   Epoch {epoch+1:3d} — loss: {logs.get('loss',0):.4f} acc: {logs.get('accuracy',0):.4f} val_acc: {logs.get('val_accuracy',0):.4f}"
        ) if (epoch + 1) % 5 == 0 else None
    )
]

print("⌃⌃ Re-training model to save compatible checkpoint...")
history = model.fit(
    X_train_s, y_train,
    epochs=MAX_EPOCHS,
    batch_size=BATCH_SIZE,
    validation_data=(X_val_s, y_val),
    callbacks=cb_list,
    verbose=0
)
print(f"\n✅ New checkpoint saved to: {checkpoint_path}")

"""
# ╔═══════════════════════════════════════════════════
# ║  CELL 13 — Comprehensive Evaluation                                 
# ╚═══════════════════════════════════════════════════"""

model = keras.models.load_model(
    '/tmp/task2_adv_best_v2.keras',
    custom_objects={
        'FocalLoss': FocalLoss,
        'freq_pooling': freq_pooling,
        'temporal_pooling': temporal_pooling
    },
    safe_mode=False
)
print("✅ Model loaded successfully from the new compatible checkpoint!")

"""
# ╔═══════════════════════════════════════════════════
# ║  CELL 14 — t-SNE Embedding Visualization                            
# ║                                                                     
# ║  t-SNE projects the 256-dimensional emotion embeddings (from the   
# ║  layer just before the final Dense) down to 2D, so we can see      
# ║  whether the model has learned to cluster emotions in its           
# ║  internal representation space.                                     
# ╚══════════════════════════════════════════════════"""

print("🔭 Computing t-SNE embedding visualization...")
print("   (This takes ~1–3 minutes)\n")

# Build a sub-model that outputs the 256-dim embedding vector
embed_model  = keras.Model(
    inputs  = model.input,
    outputs = model.get_layer('embedding').output,
    name    = 'embedding_extractor'
)

# Get embeddings for the ENTIRE test set
embeddings_256d = embed_model.predict(X_test_s, verbose=0)
print(f"   Embedding shape : {embeddings_256d.shape}")

# t-SNE: reduce 256 → 2 dimensions
tsne      = TSNE(n_components=2, perplexity=30, max_iter=1000,
                 random_state=RANDOM_SEED, init='pca', learning_rate='auto')
emb_2d    = tsne.fit_transform(embeddings_256d)
print(f"   t-SNE complete  : {emb_2d.shape}")

# Plot
fig, ax = plt.subplots(figsize=(12, 9))
fig.patch.set_facecolor('white')
ax.set_facecolor('#f0f0f0')

for i, emotion in enumerate(EMOTION_NAMES):
    mask   = y_test == i
    color  = EMOTION_COLORS.get(emotion, '#333333')
    emoji  = EMOTION_EMOJI.get(emotion, '')
    ax.scatter(emb_2d[mask, 0], emb_2d[mask, 1],
               c=color, label=f'{emoji} {emotion}',
               alpha=0.75, s=50, edgecolors='white', linewidths=0.3)

ax.set_title("🔭 t-SNE of Emotion Embeddings (256-D → 2-D)\n"
             "Tight clusters = model learned distinct emotion representations",
             fontsize=13, fontweight='bold', pad=15)
ax.legend(loc='upper right', fontsize=10, framealpha=0.9)
ax.set_xlabel("t-SNE Dimension 1", fontsize=10)
ax.set_ylabel("t-SNE Dimension 2", fontsize=10)
ax.grid(True, alpha=0.3, linestyle='--')

plt.tight_layout()
plt.savefig('/tmp/task2_tsne.png', dpi=150, bbox_inches='tight')
plt.show()
print("💾 t-SNE chart saved → /tmp/task2_tsne.png")

"""
# ╔════════════════════════════════════════════════════
# ║  CELL 15 — Save All Assets                                          
# ╚═══════════════════════════════════════════════════"""

print("💾 Saving model and assets...")

# Save scaler and label encoder
with open('/tmp/task2_scaler.pkl', 'wb') as f: pickle.dump(scaler, f)
with open('/tmp/task2_le.pkl',     'wb') as f: pickle.dump(le, f)

# Get accuracy from the last evaluation state
test_acc = model.evaluate(X_test_s, y_test, verbose=0)[1]

# Save inference config
config = {
    'emotion_names' : EMOTION_NAMES,
    'emotion_emoji' : EMOTION_EMOJI,
    'emotion_colors': EMOTION_COLORS,
    'num_classes'   : NUM_CLASSES,
    'n_mfcc'        : N_MFCC,
    'time_steps'    : TIME_STEPS,
    'sample_rate'   : SAMPLE_RATE,
    'duration'      : DURATION,
    'hop_length'    : HOP_LENGTH,
    'n_fft'         : N_FFT,
    'test_accuracy' : float(test_acc)
}
with open('/tmp/task2_config.pkl', 'wb') as f: pickle.dump(config, f)

print("✅ All assets saved:")
print("   /tmp/task2_adv_best_v2.keras ← full model")
print("   /tmp/task2_scaler.pkl       ← StandardScaler")
print("   /tmp/task2_le.pkl           ← LabelEncoder")
print("   /tmp/task2_config.pkl       ← configuration")

"""
# ╔═════════════════════════════════════════════════════
# ║  CELL 16 — Helper Functions for Live Inference                      ║
# ╚════════════════════════════════════════════════════"""

# Keep a session-level prediction history list
prediction_history = []


def generate_audio_viz(y_wav, sr, audio_path):
    """
    Generates a 3-panel visualization for any uploaded audio file:
      Panel 1 — Waveform
      Panel 2 — Mel Spectrogram
      Panel 3 — MFCC (channel 0 of 3-ch feature)
    Returns the saved image path.
    """
    fig, axes = plt.subplots(1, 3, figsize=(16, 4))
    fig.suptitle("🔬 Live Audio Feature Analysis", fontsize=13, fontweight='bold')

    # Waveform
    t = np.linspace(0, DURATION, len(y_wav))
    axes[0].plot(t, y_wav, color='#3498db', linewidth=0.8, alpha=0.9)
    axes[0].fill_between(t, y_wav, alpha=0.25, color='#3498db')
    axes[0].set_title("Waveform",   fontweight='bold');  axes[0].set_xlabel("Time (s)")
    axes[0].set_ylabel("Amplitude")

    # Mel Spectrogram
    S    = librosa.feature.melspectrogram(y=y_wav, sr=sr, n_mels=N_MELS,
                                           n_fft=N_FFT, hop_length=HOP_LENGTH)
    S_db = librosa.power_to_db(S, ref=np.max)
    img  = librosa.display.specshow(S_db, sr=sr, hop_length=HOP_LENGTH,
                                     ax=axes[1], cmap='magma',
                                     x_axis='time', y_axis='mel')
    axes[1].set_title("Mel Spectrogram", fontweight='bold')
    plt.colorbar(img, ax=axes[1], format='%+2.0f dB')

    # MFCC (static channel only for clarity)
    mfcc = librosa.feature.mfcc(y=y_wav, sr=sr, n_mfcc=N_MFCC,
                                  n_fft=N_FFT, hop_length=HOP_LENGTH)
    img2 = librosa.display.specshow(mfcc, sr=sr, hop_length=HOP_LENGTH,
                                     ax=axes[2], cmap='viridis',
                                     x_axis='time', y_axis='mel')
    axes[2].set_title("MFCC (40 Coefficients)", fontweight='bold')
    plt.colorbar(img2, ax=axes[2])

    plt.tight_layout()
    out_path = '/tmp/task2_live_viz.png'
    plt.savefig(out_path, dpi=130, bbox_inches='tight')
    plt.close(fig)
    return out_path


def predict_emotion(audio_path):
    """
    Full inference pipeline: load audio → extract 3-ch feature →
    scale → predict → format result + generate visualization.
    Returns (result_text, visualization_image_path).
    """
    if audio_path is None:
        return "❌ Please upload or record an audio file first.", None

    try:
        # Load audio
        y_wav, _  = librosa.load(audio_path, sr=SAMPLE_RATE, duration=DURATION)
        y_wav     = librosa.util.fix_length(y_wav, size=int(SAMPLE_RATE * DURATION))

        # Extract 3-channel feature
        feat_3ch  = extract_3ch_feature(audio_path, augment=False)
        if feat_3ch is None:
            return "❌ Could not process audio. Please try a clearer recording.", None

        # Scale using saved scaler
        feat_flat = feat_3ch.reshape(1, -1)
        feat_s    = scaler.transform(feat_flat).reshape(1, N_MFCC, TIME_STEPS, 3)

        # Predict
        probs         = model.predict(feat_s, verbose=0)[0]
        top5_idx      = np.argsort(probs)[::-1][:5]
        pred_idx      = top5_idx[0]
        pred_emotion  = EMOTION_NAMES[pred_idx]
        pred_emoji    = EMOTION_EMOJI.get(pred_emotion, '🎙️')
        confidence    = probs[pred_idx] * 100

        # Confidence interpretation
        if   confidence >= 75: certainty = "Very Confident"
        elif confidence >= 55: certainty = "Confident"
        elif confidence >= 40: certainty = "Moderate"
        else:                  certainty = "Uncertain"

        # Format result text
        result  = "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        result += "  🎙️  EMOTION RECOGNITION RESULT\n"
        result += "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"
        result += f"  {pred_emoji}  Emotion     :  {pred_emotion.upper()}\n"
        result += f"  📊  Confidence :  {confidence:.1f}%  ({certainty})\n\n"
        result += "  🔝 Top-5 Predictions:\n"
        for rank, idx in enumerate(top5_idx):
            emo    = EMOTION_NAMES[idx]
            emoji  = EMOTION_EMOJI.get(emo, '')
            pct    = probs[idx] * 100
            bar    = '█' * int(pct / 5) + '░' * (20 - int(pct / 5))
            result += f"  {rank+1}. {emoji} {emo:12s} {bar} {pct:5.1f}%\n"
        result += f"\n  🤖 Architecture :  SE-CNN → MHA → BiLSTM\n"
        result += f"  🎯 Test Accuracy :  {test_acc*100:.2f}%\n"
        result += "\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
        result += "  ⚠️  Educational project only."

        # Save to session history
        prediction_history.append({
            'emotion': pred_emotion, 'confidence': f"{confidence:.1f}%",
            'file': os.path.basename(audio_path)
        })

        # Generate visualization
        viz_path = generate_audio_viz(y_wav, SAMPLE_RATE, audio_path)
        return result, viz_path

    except Exception as e:
        return f"❌ Error during prediction: {str(e)}", None


def get_history():
    """Returns the session prediction history as a DataFrame."""
    if not prediction_history:
        return pd.DataFrame(columns=['#','Emotion','Confidence','File'])
    df_hist = pd.DataFrame(prediction_history)
    df_hist.index += 1
    df_hist.index.name = '#'
    df_hist.columns    = ['Emotion','Confidence','File']
    return df_hist.reset_index()

"""
# ╔═══════════════════════════════════════════════════
# ║  CELL 17 — Build & Launch Advanced Gradio Web App (6 Tabs)         
# ╚══════════════════════════════════════════════════"""

with gr.Blocks(
    theme = gr.themes.Soft(
        primary_hue   = "indigo",
        secondary_hue = "blue",
        neutral_hue   = "slate"
    ),
    title = "🎙️ Advanced Speech Emotion Recognition"
) as app:

    gr.Markdown(f"""
    <div style='text-align:center; padding:20px 0'>
        <h1 style='font-size:2em; margin-bottom:4px'>🎙️ Advanced Speech Emotion Recognition</h1>
        <p style='color:#666; font-size:1.05em'>
            <b>CodeAlpha ML Internship — Task 2</b> &nbsp;·&nbsp;
            Developer: <b>Taj Wali Khan</b> &nbsp;·&nbsp;
            Model: <b>SE-CNN → MHA → BiLSTM</b> &nbsp;·&nbsp;
            Test Accuracy: <b>{test_acc*100:.2f}%</b>
        </p>
    </div>
    """)

    with gr.Tabs():
        with gr.Tab("🎤 Analyze Speech"):
            with gr.Row():
                with gr.Column():
                    audio_input = gr.Audio(label="🎙️ Speech Input", type="filepath", sources=["upload", "microphone"])
                    btn_analyze = gr.Button("🔬 Analyze Emotion", variant="primary")
                with gr.Column():
                    result_output = gr.Textbox(label="📊 Analysis Result", lines=15)
            audio_viz = gr.Image(label="🔬 Audio Feature Visualization")
            btn_analyze.click(fn=predict_emotion, inputs=[audio_input], outputs=[result_output, audio_viz])

        with gr.Tab("📝 Session History"):
            btn_refresh = gr.Button("🔄 Refresh History")
            history_tbl = gr.DataFrame(value=get_history(), label="Prediction Log")
            btn_refresh.click(fn=get_history, inputs=[], outputs=[history_tbl])

        with gr.Tab("📊 Model Performance"):
            gr.Image('/tmp/task2_tsne.png', label="t-SNE Embedding Space")
            gr.Image('/tmp/task2_feature_maps.png', label="Extraction Process (MFCC Delta Delta2)")

app.launch(share=True, debug=False)
print("\n🚀 App is live! Click the public URL above to open it.")